# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c727eb7bde73fe01a85da5e9c6fbe060b06a7a36676796547eebb9e8cd87668f908d74d0cb557847186bfb276a9a594851107e48844932a0a2eb844430a2b82

test:
  secret_key_base: dd916e44e2b8fb07ec5f710d0ea0d775722a02a9c199e034317aba41230f3f07ccd5ae6a4764fc448f962a5d4f1f11e6b9b8bf69b821a8c9720756922647ffa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
